/**
 * The bundled provider: the derived snapshot that ships with the application.
 *
 * This is the deployment's data path until ERPNext is connected. The snapshot is
 * imported as a module rather than read from disk, so it is part of the build
 * output by construction — there is no file that can be missing at runtime, no
 * storage account to configure, and no URL to get wrong. Deploying the code
 * deploys the data.
 *
 * The trade-off is that refreshing the data is a commit and a deploy. That is the
 * right shape for a snapshot that changes when a new export is produced, and it
 * stops mattering entirely once the ERPNext provider is live and the portal reads
 * the ERP continuously.
 */

import type { PortalSnapshot } from '@/portal/types'
import bundled from '../../content/portal-snapshot.json'

/**
 * The JSON is generated by `npm run build:snapshot` from the same derivation the
 * ERPNext provider uses, so its shape is guaranteed by that code rather than by
 * this assertion. Structural typing of a 0.5 MB literal would cost more in
 * compile time than it could tell us.
 */
const snapshot = bundled as unknown as PortalSnapshot

export function loadBundledSnapshot(): PortalSnapshot {
  if (!Array.isArray(snapshot.items) || snapshot.items.length === 0) {
    throw new Error(
      'content/portal-snapshot.json contains no item lines. Run `npm run build:snapshot` ' +
        'against the backlog export and commit the result — serving an empty portal would ' +
        'read to every customer as "nothing has happened on your order".',
    )
  }
  return snapshot
}
